language: node_js

node_js:
  - 16
  - 14
  - 12

before_script:
  - npm prune

script:
  - npm run prettier:check
  - npm run test
  - npm run cover
  - npm run check-coverage
  - npm run build

after_success:
  - npm run coveralls
