language: node_js

node_js:
  - 14
  - 12
  - 10

before_script:
  - npm prune

script:
  - npm run test
  - npm run cover
  - npm run check-coverage
  - npm run build

after_success:
  - npm run coveralls
